### ISSUE TITLE
Led problem on Windows10

### ISSUE THREAD

**Issue by gianmarco-mameli** [spuder/MuteMe-arduino#5]
Hi spuder, thanks for this awesome project, I've forked your repo and configured 2 variants, one for an Arduino Pro Micro connected to a Neopixel ring light, and one for a Adafruit Trinkey.
All work like a charm in my mac machine, but when i try to use the devices on a windows machine for work, only the button part works, the led stays off.
I've tried to monitor the output with platformio and vscode, and the rawhid data arrives empty, like 0/0 and similar.
Do you have any idea why is not working, or if maybe it's more appropriate to open the issue on the nicohood/hid project

Thanks

**Comment by spuder** [comment]
I'm so glad you found the project and are trying this out. NeoPixels do make a lot of sense. I don't know why I didn't do that initially. 

I've not tested this on windows, only mac; however the protocol theoretically should be the same. I've not seen anything in the [mute me technical docs](https://muteme.com/pages/muteme-hid-key?_pos=1&_sid=2af9f1e4c&_ss=r) that would behave differently on windows. 

A couple of ideas
1. I'll plug mine into a windows computer and see if I get the same results
2. USB power limitations? 
3. Driver need to be installed? 
4. Which HID is in use? Try original instead of prototype

5. Does hidutil run on windows? If so it would be interesting to see a full dump

```
hidapitester --vidpid 20A0:42DB --open --length 64 --read-input-forever --close
```

6. Can you write to the LED manually? 

```
hidapitester --vidpid 20A0/42DB --open --length 1 --send-feature 0x25 --close
```

7. What version of muteme software? They may have broken the 'prototype' functionality.

**Comment by spuder** [comment]
I just tested my arduino mute me and I'm seeing the same behavior. 

The LED doesn't light up on windows, but it does on Mac.

My suggestion is to compile with DEBUG enabled to try and see what is happening.

I suspect windows is using a different frame size so the 64 bits it is expecting is not being received (main.cpp line 115)

**Comment by gianmarco-mameli** [comment]
Hi, this is the repeated output on a windows machine with debug mode on, and the muteme app open
```
parseEffect: 0
bright
hidData: 0 / 0
ones: 0 / 0
tens: 0 / 0

parseEffect: 0
bright
hidData: 0 / 0
ones: 0 / 0
tens: 0 / 0
```

As mentioned before the button works perfectly, but the led don't

**Comment by cbattlegear** [comment]
I am also seeing this issue too (building on a Trinket M0) Button is working but led is not, currently seeing mostly 0/0 spam, but I do see some outputs of:

Invalid/Undocumented data: 80/8
Invalid/Undocumented data: 812/C8
Invalid/Undocumented data: 111/1B

Running MuteMe-Client v0.15.2.stable (win_64)

What info would you like on the hidapitester? I essentially just see a bunch of "zeros"

I did do a USB trace on the device out of curiosity and I am seeing 36 BULK_OR_INTERRUPT_TRANSFER messages between every normal class.

Any other info you need happy to help, I am going to keep digging into this to see if I can pull anything together.

**Comment by cbattlegear** [comment]
Quick update, patched in reading 64k every message and it is working perfectly now, will clean my code up (added a bunch of testing garbage and a DotStar) and see if I can throw in a PR.

**Comment by gianmarco-mameli** [comment]
Hi, thank you great, i'll wait for your mod. When I'm sure all it's ok i'm going to clean up my code and commit the NeoPixel and Trinkey variations

**Comment by spuder** [comment]
Awesome work! I'm so glad you found that.

**Comment by spuder** [comment]
Thanks so much for your help. 
I'll close this issue since it looks like #6 has fixed the LED issue on both windows and mac. 

Also, as a side note, I've linted the code with `clang-format -i src/*.cpp`, so if you open a PR for neopixel support you may want to lint first to avoid conflicts. (Eventually I'll figure out why automatic linting isn't working in #7 )
